### ISSUE TITLE
lxml missing?

### ISSUE THREAD

**Issue by duel007** [timhaak/docker-couchpotato#4]
Latest version seems to be missing the lxml package for html scraping. Manually installing python-lxml resovles issue.

**Comment by timhaak** [comment]
Just added it to the docker file as part of the pip installs.

It should start rebuilding soon.

Please pull in an our or two from now and let me know if there are any problems.

**Comment by duel007** [comment]
Doesn't look like it's rebuilt on the docker hub yet.
