### ISSUE TITLE
can't access to my media folder

### ISSUE THREAD

**Issue by boistordu** [timhaak/docker-couchpotato#8]
hi, I have linked -v /media:/data I don't get it in the UI, it's all blank....

**Comment by boistordu** [comment]
+ there is something wierd, shouldn't be a separation where my media files are and where the database are? like to not mess with other things like plex server? 
the :/data has created dirs like logs database db_backup custom_plugins etc .... I don't want to have those where my media files are stored....

**Comment by timhaak** [comment]
Hi

I'll look into this once I have time.

For now will track it via  #9. So that there's one place.
